In [26]:
import numpy as np

# Covariance Matrix

In [27]:
x=np.array([[3,12,30],[16,6,45],[5,8,11]])

In [28]:
x1=np.average(x, axis=0)

In [29]:
m=x-x1
print(m)

[[ -5.           3.33333333   1.33333333]
 [  8.          -2.66666667  16.33333333]
 [ -3.          -0.66666667 -17.66666667]]


In [30]:
convm=np.dot(m.T,m)/2  # or conv=np.cov(m.T)
convm

array([[ 49.        , -18.        ,  88.5       ],
       [-18.        ,   9.33333333, -13.66666667],
       [ 88.5       , -13.66666667, 290.33333333]])

# ConFusion Matrix

In [31]:
y=[0,0,1,1,1,1,0]
p=[0,1,1,1,1,0,0]
#accuracy,recall,precision,TPR,FPR
#1=positive, 0=negative
tp=0
tn=0
fp=0
fn=0
for i in range(7):
    if(y[i]==1 and p[i]==1):
        tp=tp+1
    elif(y[i]==0 and p[i]==0):
        tn=tn+1
    elif(y[i]==1 and p[i]==0):
        fn=fn+1
    elif(y[i]==0 and p[i]==1):
        fp=fp+1
    
        
print(tp,tn,fp,fn)
    
accuracy=(tp+tn)/len(y)
recall=tp/(tp+fn)
precision=tp/(tp+fp)
tpr=tp/(tp+fn)
fpr=fp/(fp+tn)
print("Accuracy= ",accuracy*100,"%")
print("Recall= ",recall*100,"%")
print("Precision= ",precision*100,"%")
print("TPR= ",tpr*100,"%")
print("FPR= ",fpr*100,"%")

    


3 2 1 1
Accuracy=  71.42857142857143 %
Recall=  75.0 %
Precision=  75.0 %
TPR=  75.0 %
FPR=  33.33333333333333 %


# Neural network

In [32]:
w=np.array([[2.7,0.8,0.7],
           [3,-6,6.4],
           [3,6.6,-6.3]])
w2=np.array([7.3,6.0,-8.8,-8.8])

In [33]:
x=[1,1,0]
h1=np.dot(w[0].T,x)
h2=np.dot(w[1].T,x)
h3=np.dot(w[2].T,x)
print(h1,h2,h3)

3.5 -3.0 9.6


In [34]:
h1=1/(1+np.exp(-h1))
h2=1/(1+np.exp(-h2))
h3=1/(1+np.exp(-h3))

In [35]:
print(h1,h2,h3)

0.9706877692486436 0.04742587317756678 0.9999322758503804


In [36]:
h=[1,h1,h2,h3]

In [37]:
y=np.dot(w2.T,h)
y=1/(1+np.exp(-y))

In [38]:
y

0.980302604863478

In [39]:
#w2[i]=2(pr-y)*pr(1-pr)*h[i]
#w[i][j]=2(pr-y)*pr(1-pr)*w2[i+1]*h[i+1](1-h[i+1])*x[j]

# K-Means

In [40]:
x=np.array([[5,4],[4,6],[7,10],[1,3],[7,2],[8,9]])

In [41]:
print(x)
x[0]

[[ 5  4]
 [ 4  6]
 [ 7 10]
 [ 1  3]
 [ 7  2]
 [ 8  9]]


array([5, 4])

In [42]:
d=[]
d2=[]
g1=[]
g2=[]
#c1=[52, 70]
#c2=[64, 19]
c1=[4,4]
c2=[6,5]
for i in range(len(x)):
    d.append(np.sqrt((x[i][0]-c1[0])**2+(x[i][1]-c1[1])**2))
    d2.append(np.sqrt((x[i][0]-c2[0])**2+(x[i][1]-c2[1])**2))
    if(d[i]<d2[i]):
        g1.append(x[i])
    else:
        g2.append(x[i])
        
print(g1)
print(g2)

[array([5, 4]), array([4, 6]), array([1, 3])]
[array([ 7, 10]), array([7, 2]), array([8, 9])]


In [43]:
av=np.mean(g1,axis=0)
av2=np.mean(g2,axis=0)

In [44]:
av,av2

(array([3.33333333, 4.33333333]), array([7.33333333, 7.        ]))