In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

In [3]:
X=np.array([[8,7],[4,10],[9,7],[7,10],[9,6],[4,8],[10,10],[2,7],[8,3],[7,5],[4,4],[4,6],[1,3],[2,5]])
Y=np.array([1,1,1,1,1,1,1,-1,-1,-1,-1,-1,-1,-1])

In [4]:
Xa= np.c_[np.ones(X.shape[0]), X]
print(Xa)

[[ 1.  8.  7.]
 [ 1.  4. 10.]
 [ 1.  9.  7.]
 [ 1.  7. 10.]
 [ 1.  9.  6.]
 [ 1.  4.  8.]
 [ 1. 10. 10.]
 [ 1.  2.  7.]
 [ 1.  8.  3.]
 [ 1.  7.  5.]
 [ 1.  4.  4.]
 [ 1.  4.  6.]
 [ 1.  1.  3.]
 [ 1.  2.  5.]]


In [5]:
w=np.random.rand(3)
print(w)

[0.89752093 0.23161288 0.4126983 ]


In [6]:
def predict(w,Xa):
    h=[]
    for x in range(len(Xa)):
        val=0
        Xa1=Xa[x]
        for ix,iy in zip(Xa1,w):
            val+=ix*iy
        if(val>=0):
            h.append(1)
        elif(val<0):
            h.append(-1)
    return h


In [7]:
def missclass(h,Y):
    miss=[]
    for i in range(len(Y)):
        if(h[i]!=Y[i]):
            miss.append(i)
    return miss


In [8]:
w=np.random.rand(3)
h=predict(w,Xa)
miss=missclass(h,Y)
while (len(miss)>0):
    rn=np.random.choice(miss)
    rx=Xa[rn]
    ry=Y[rn]
    w=w+rx*ry
    h=predict(w,Xa)
    miss=missclass(h,Y)

print(w)

[-24.16186316   0.60491992   3.20720867]


In [9]:
p=predict(w,Xa)
print(p)

[1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1]


In [10]:
accuracy_score(Y, p)*100

100.0

In [20]:
in_x=np.array([[1,2],[4,5],[12,7],[16,10],[20,5],[5,8],[10,10]])
in_y=[1,1,-1,-1,1,-1,-1]
b=0.5
in_w=[-0.2,0.1]

In [25]:
def predict2(w,Xa,b):
    h=[]
    for x in range(len(Xa)):
        val=0
        Xa1=Xa[x]
        #print(Xa1)
        val=np.dot(Xa[x],w)+b
        #for ix,iy in zip(Xa1,w):
            #val+=ix*iy+b
            #print(ix,iy)
        print("value= ",val)
        if(val>=0):
            h.append(1)
        elif(val<0):
            h.append(-1)
    print(h)
    return h

In [26]:
h=predict2(in_w,in_x,b)

value=  0.5
value=  0.19999999999999996
value=  -1.2000000000000002
value=  -1.7000000000000002
value=  -3.0
value=  0.30000000000000004
value=  -0.5
[1, 1, -1, -1, -1, 1, -1]
