In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
X=np.array([[8,7],[4,10],[9,7],[7,10],[9,6],[4,8],[10,10],[2,7],[8,3],[7,5],[4,4],[4,6],[1,3],[2,5]])
Y=np.array([1,1,1,1,1,1,1,-1,-1,-1,-1,-1,-1,-1])
#print(len(X),len(Y))
#for x in range(len(X)):
    #print(X[x],Y[x])

In [6]:
Xa= np.c_[np.ones(X.shape[0]), X]
print(Xa)

[[ 1.  8.  7.]
 [ 1.  4. 10.]
 [ 1.  9.  7.]
 [ 1.  7. 10.]
 [ 1.  9.  6.]
 [ 1.  4.  8.]
 [ 1. 10. 10.]
 [ 1.  2.  7.]
 [ 1.  8.  3.]
 [ 1.  7.  5.]
 [ 1.  4.  4.]
 [ 1.  4.  6.]
 [ 1.  1.  3.]
 [ 1.  2.  5.]]


In [7]:
w=np.random.rand(3)
print(w)


[0.56829077 0.88098233 0.61320349]


In [8]:
def predict(w,Xa):
    h=[]
    for x in range(len(Xa)):
        val=0
        Xa1=Xa[x]
        for ix,iy in zip(Xa1,w):
            val+=ix*iy
        if(val>0):
            h.append(1)
        elif(val<0):
            h.append(-1)
    return h


In [9]:
def missclass(h,Y):
    miss=[]
    for i in range(len(Y)):
        if(h[i]!=Y[i]):
            miss.append(i)
    return miss


In [10]:
#rn=np.random.choice(miss)
#print(rn)
#rx=Xa[rn]
#ry=Y[rn]
#print(rx)
#print(ry)

#print(w)
#w=w+rx*ry
#print(w)

In [11]:
w=np.random.rand(3)
h=predict(w,Xa)
miss=missclass(h,Y)
while (len(miss)>0):
    rn=np.random.choice(miss)
    rx=Xa[rn]
    ry=Y[rn]
    w=w+rx*ry
    h=predict(w,Xa)
    miss=missclass(h,Y)

print(w)

[-61.09246844   2.3758302    8.01701216]


In [12]:
p=predict(w,Xa)
print(p)

[1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1]


In [13]:
u=[1,5,5]
p=predict(w,[u])
print(p)

[-1]
