#### CSE 452: Neural Networks and Fuzzy Systems Lab
Spring-2020, Dept. of CSE, NEUB <br>

#### Student Info
<b>Name:</b> Hamiduzzaman Noyon<br>
<b>Reg. No:</b> 160303020004

### Assignment  3: Fully Connected Layer (Feedforward+Backprop)
<b>This assignment contains three tasks</b><br>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X=np.array([[1, 2], [4, 5], [12, 7], [16, 10], [20, 5], [5, 8]  ])
y=np.array([[0,1], [0,1], [1,0], [1,0],  [0,1], [1,0] ])

In [3]:
print(y)

[[0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]]


In [4]:
X.shape

(6, 2)

In [5]:
b=np.array([0.5, 0.6])
w=np.array([ [0.1,0.2], [0.3,0.4] ])

<b>Softmax</b>
$$Let, a=[a_0, a_1, a_2, ..]$$
$$S_i=\frac{e^{a_i}}{\sum_{k=0}^{N} {e^{a_k}}}$$

<b>Task 1: calculate feedforward output</b><br><br>
$\hat{y}=softmax(X.w+b)$

Output should look like the following. <br>

[[0.401 0.599] <br>
 [0.269 0.731] <br>
 [0.119 0.881] <br>
 [0.063 0.937] <br>
 [0.069 0.931] <br>
 [0.198 0.802]]

In [6]:
def softmax(z):
    a=[]
    for i in z:
        b0=np.exp(i[0])/(np.exp(i[0])+np.exp(i[1]))
        b1=np.exp(i[1])/(np.exp(i[0])+np.exp(i[1]))
        a.append([round(b0,3),round(b1,3)])
    return a

In [7]:
z=np.dot(X,w)+b
pr_y=softmax(z)
print(np.array(pr_y))

[[0.401 0.599]
 [0.269 0.731]
 [0.119 0.881]
 [0.063 0.937]
 [0.069 0.931]
 [0.198 0.802]]


<b>Task 2: calculate log loss</b><br><br> 
$$L_i = - y_i* \sum \log (A_i)$$
\begin{equation*}
L =\frac{1}{N} \sum_i L_i 
\end{equation*}

Output should look like the following. <br>
Loss: [0.513 0.313 2.127 2.765 0.072 1.62 ] <br>
average loss: 1.2351

In [9]:
def loss(y,a):
    l=[]
    for i in range(len(y)):
        temp=-y[i][0]*np.log(a[i][0])-y[i][1]*np.log(a[i][1])
        l.append(round(temp,3))
    return l

In [12]:
l=loss(y,pr_y)
print("loss= ",l)
avg_loss=np.mean(l)
print("average loss= ",round(avg_loss,3))

loss=  [0.512, 0.313, 2.129, 2.765, 0.071, 1.619]
average loss=  1.235


<b>Task 3: calculate gradient</b>

$$dz=\hat{y}-y$$ 
$$dw=\frac{1}{N} ( X^T.dz )$$   
$$db=\frac{1}{N} \sum dz $$ 

Dimension check: y-yh= (2xN).(NX2)=(2x2) 

dw should look like below, <br>
[[-4.452,  4.452], <br>
[-3.243,  3.243]])

db should look like below<br>
[[-0.313,  0.313]]

In [13]:
dz=(pr_y-y)
dw=(1/len(y))*np.dot(X.T,dz)
print("dw\n",dw)
db=np.mean(dz,axis=0)
print("db\n",db)

dw
 [[-4.45283333  4.45283333]
 [-3.2435      3.2435    ]]
db
 [-0.3135  0.3135]


### Submission: Honor Code
Plese type the following in the next cell. Replace the underlined text with your own. 

I am <u>Hamiduzzaman Noyon</u> bearing registration no. <u>160303020004</u> hereby declaring that I myself did my assignments, I didn't directly copy any code from others. I have a complete understanding of my code and can explain. I respect this honor code and I believe it will be useful to maintain academic integrity.<br>

Name: <u>Hamiduzzaman Noyon</u><br>
Date: <u>25/07/20</u>

_start writing here_