#### CSE 452: Neural Networks and Fuzzy Systems Lab
Spring-2020, Dept. of CSE, NEUB <br>

#### Student Info
<b>Name:</b> Hamiduzzaman Noyon<br>
<b>Reg. No:</b> 160303020004

### Assignment  2: Hopfield
<b>This assignment contains three tasks</b><br>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

<b>Let's train 3 pattern. Each pattern has length of four</b>

In [2]:
#initialize w
n=4
w=np.zeros((n,n))
print(w)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
#patterns to train.
x1=np.array([1,1,-1,-1])
x2=np.array([-1,1,1,-1])
x3=np.array([1,-1,-1,1])

In [4]:
#make 1x4 vector form
x1=x1.reshape(1,-1)
x2=x2.reshape(1,-1)
x3=x3.reshape(1,-1)

In [5]:
print('x1 shape:',x1.shape)
print('x2 shape:',x2.shape)
print('x3 shape:',x3.shape)

x1 shape: (1, 4)
x2 shape: (1, 4)
x3 shape: (1, 4)


### Training pattern


$$ dw=x.x^T -I \space \space \\ where \space \space I =\space identity \space matrix.$$  
$$w=w+dw$$

<b> Task 1:</b><br>
Train x1 and update w.<br>
<b>updated w</b> should look like the following. 

[[ 0.  1. -1. -1.]<br>
 [ 1.  0. -1. -1.]<br>
 [-1. -1.  0.  1.]<br>
 [-1. -1.  1.  0.]]

In [6]:
n=4
w=np.zeros((n,n))
dw=np.dot(x1.T,x1)-np.identity(4)
w=w+dw
print(w)

[[ 0.  1. -1. -1.]
 [ 1.  0. -1. -1.]
 [-1. -1.  0.  1.]
 [-1. -1.  1.  0.]]


<b> Task 2:</b><br>
Now, train x2 and then x3<br>
After training x3, updated <b>w</b> should look like the following<br>
[[ 0. -1. -3.  1.]<br>
 [-1.  0.  1. -3.]<br>
 [-3.  1.  0. -1.]<br>
 [ 1. -3. -1.  0.]]

In [7]:
dw=np.dot(x2.T,x2)-np.identity(4)
w=w+dw
dw=np.dot(x3.T,x3)-np.identity(4)
w=w+dw
print(w)

[[ 0. -1. -3.  1.]
 [-1.  0.  1. -3.]
 [-3.  1.  0. -1.]
 [ 1. -3. -1.  0.]]


<b>Task 3:</b> Energy
After training x3, calculate energy.<br>
Output should be = -10

neurons are so interconnected, that they may cause oscillation, or instability. This is called the “energy” of a hopfield net.


$$E=\frac{−1}{2} \sum_{j=1}^n  \sum_{i=1}^n w_{ij}x_i x_j$$

In terms of linear algebra, simpler version is 
$$E = -\frac{1}{2} x^T.W.x$$

In [8]:
e=0
for x in range (len(w)):
    for y in range(len(w[x])):
        e=e+w[x][y]*x3[0][x]*x3[0][y]
e=e*-0.5
print("Energy= ",e)

Energy=  -10.0


### Submission: Honor Code
Plese type the following in the next cell. Replace the underlined text with your own. 

I am <u>Hamiduzzaman Noyon</u> bearing registration no. <u>160303020004</u> hereby declaring that I myself did my assignments, I didn't directly copy any code from others. I have a complete understanding of my code and can explain. I respect this honor code and I believe it will be useful to maintain academic integrity.<br>

Name: <u>Hamiduzzaman Noyon</u><br>
Date: <u>25/07/20</u>

_start writing here_